Feature/concurrency example
sagar-jadhav/go-examples pull request #14
Opened 2019-10-01 21:51 UTC by itmecho

2019-10-02 02:44 UTC, sagar-jadhav requested changes

2019-10-02 02:44 UTC, sagar-jadhav commented on src/concurrency.go
> +func main() {
Add description here about program. For e.g. 
- Purpose of program
- How concurrency achieve here?
- Call out packages & special methods used in the program

2019-10-02 02:46 UTC, sagar-jadhav commented
Thank you @itmecho for contribution 👍

2019-10-02 02:47 UTC, sagar-jadhav commented
Assign #6 to yourself

2019-10-04 18:09 UTC, rajkumarGosavi requested changes
Can elaborate more to make the example easy to understand for first time developers new to the topic of concurrency

2019-10-04 18:09 UTC, rajkumarGosavi commented on src/concurrency.go
> +}
One can try dividing this example in 2 parts.
1. Only explaining about Go routines
2. Go routines + channels

2019-10-30 14:23 UTC, sagar-jadhav commented
Closing the #14 as issue got already resolved via #82.

Thank you @itmecho for your contribution 👍

2019-10-30 14:23 UTC, closed without merging