Go example for Command Line Arguments
sagar-jadhav/go-examples pull request #16
Opened 2019-10-02 09:50 UTC by rishinair11

2019-10-04 07:03 UTC, sagar-jadhav commented
Linking with #2

2019-10-04 07:05 UTC, sagar-jadhav commented
@rishinair11 Please add details about changes added. It will set context for reviewers.

2019-10-04 07:16 UTC, ilmanzo requested changes
generally very good; only could be more significant in a couple of places.

2019-10-04 07:16 UTC, ilmanzo commented on src/panic-defer-recover/defer.go
> +	//Defer is used to ensure that a function call is performed later
since the purpose is educational, I'd be more specfiic here; It's not only "later" but when the function returns to the caller

2019-10-04 07:16 UTC, ilmanzo commented on src/panic-defer-recover/recover.go
> +	recoverObj := recover()
what can be the return value of recover() ? What do this object contains ?

2019-10-04 18:01 UTC, rajkumarGosavi commented on src/panic-defer-recover/panic.go
> +	if name == nil {
checking for only name argument and not for the remaining two

2019-10-04 18:03 UTC, rajkumarGosavi requested changes
Few changes to be made in src/panic-defer-recover/panic.go in the conditional statements.

2019-10-12 16:50 UTC, sagar-jadhav commented
@rishinair11 Can you please have a look on review comments?

2019-11-02 13:48 UTC, sagar-jadhav commented
Closing #16 due to inactivity. @rishinair11 Create separate PR once you are ready with changes.

2019-11-02 13:48 UTC, closed without merging