Add PR template on project
sagar-jadhav/go-examples pull request #34
Opened 2019-10-05 07:15 UTC by kazuhirodk

## Description
Add template for PR

## Issue
https://github.com/sagar-jadhav/go-examples/issues/30

2019-10-05 07:17 UTC, kazuhirodk commented on pull_request_template.md
> +Please also list any relevant details for your test configuration -->
```suggestion
Please also list any relevant details for your test configuration
```

2019-10-05 07:17 UTC, kazuhirodk commented on pull_request_template.md
> +- [ ] Test B
```suggestion
- [ ] Test B  -->
```

2019-10-07 17:24 UTC, sagar-jadhav approved these changes
Add link to Pull Request Template in README.

2019-10-07 17:26 UTC, sagar-jadhav requested changes
Incorporate Review Comments

2019-10-07 17:34 UTC, rajkumarGosavi approved these changes

2019-10-11 03:22 UTC, kazuhirodk commented
I added the template link in the readme, but in the default branch it will already be applied automatically when a pull request is opened 😸

2019-10-11 16:26 UTC, sagar-jadhav approved these changes

2019-10-11 16:27 UTC, merged

2019-10-11 16:55 UTC, rajkumarGosavi reviewed
Great!