Added documentation for if elseif and else in go
sagar-jadhav/go-examples pull request #77
Opened 2019-10-08 13:51 UTC by piyushs2894

2019-10-09 05:40 UTC, sagar-jadhav commented
Linking with #47

2019-10-09 05:41 UTC, sagar-jadhav requested changes
Add link to if-elseif-else.md in README as `if-elseif-else.html`

2019-10-09 05:41 UTC, sagar-jadhav commented on if-elseif-else.md
> +/*
Remove description from here

2019-10-09 05:41 UTC, sagar-jadhav commented on if-elseif-else.md
> +
Add description here

2019-10-09 12:52 UTC, piyushs2894 commented on if-elseif-else.md
> +/*
done.

2019-10-09 12:52 UTC, piyushs2894 commented on if-elseif-else.md
> +
done

2019-10-09 13:59 UTC, sagar-jadhav reviewed
Update link in READ me as follows:

`./if-elseif-else.html`

2019-10-10 04:44 UTC, piyushs2894 commented
Updated link in Readme

2019-10-10 14:26 UTC, sagar-jadhav approved these changes

2019-10-10 14:26 UTC, merged