add go reoutines
sagar-jadhav/go-examples pull request #78
Opened 2019-10-08 17:28 UTC by moogacs

Happy hacking :)

2019-10-09 05:58 UTC, sagar-jadhav commented
Thank you @moogacs for contribution 👍

2019-10-13 17:23 UTC, sagar-jadhav commented
@aprabhat & @rajkumarGosavi Can you please review the code changes?

2019-10-15 06:20 UTC, rajkumarGosavi requested changes

2019-10-15 06:20 UTC, rajkumarGosavi commented on src/routine.go
> +	}("going")
Please write beautiful comments about why we need to pass the context to go routine. It is an important topic
also an example where a go routine is called in a for loop will be very helpful something like
```

for ...{

    go someFunc(){

}(context)

}

```

also show how one can use multiple procs using **GOMAXPROCS**

2019-10-18 16:43 UTC, sagar-jadhav commented
@moogacs Can you please have look on review comments & incorporate suggested changes?

2019-10-19 13:08 UTC, moogacs commented
@sagar-jadhav  will do that

2019-10-30 13:53 UTC, sagar-jadhav commented
Hello @moogacs any updates on  **incorporating review comments**? Let's try to close this as early as possible. 
### 
Let me know if you require any help from our side.

2019-11-07 09:38 UTC, sagar-jadhav commented
@moogacs I am closing #78 PR due to inactivity. Please raise another PR once you ready with your changes.

2019-11-07 09:38 UTC, closed without merging