[Issue44] Added readme for Closure
sagar-jadhav/go-examples pull request #79
Opened 2019-10-08 18:11 UTC by yogesh-desai

2019-10-11 17:39 UTC, sagar-jadhav requested changes
Linking with #44

2019-10-11 17:39 UTC, sagar-jadhav commented on README.md
> +* [Closure](https://github.com/sagar-jadhav/go-examples/blob/master/src/closure.md)
Please update link as `./closure.html`

2019-10-12 07:41 UTC, rajkumarGosavi approved these changes

2019-10-12 09:55 UTC, yogesh-desai commented
Updated README.md

2019-10-12 14:48 UTC, sagar-jadhav approved these changes

2019-10-12 14:48 UTC, merged