Add documentation for http_srv example
sagar-jadhav/go-examples pull request #84
Opened 2019-10-12 17:24 UTC by davidkroell

This is the first version of the documentation for the HTTP Server added in #35.
Please review and give feedback for further improvement.

Best regards,
David

2019-10-13 05:30 UTC, sagar-jadhav requested changes

2019-10-13 05:30 UTC, sagar-jadhav commented on http_srv.md
> +The attributes fo the person, namely first- and lastname, are specified in the POST body
minor typo it should be `firstname` instead of  `first-`

2019-10-13 05:30 UTC, sagar-jadhav commented on http_srv.md
> +URL-encoded. In this example `John Doe` is used.
Add `createPerson` code snippet here as follows:

```
func createPerson(w http.ResponseWriter, r *http.Request) {
	if r.Method == "POST" {

		fn := r.FormValue("first_name")
		ln := r.FormValue("last_name")

		p := Person{
			FirstName: fn,
			LastName:  ln,
		}

		people[lastId] = p
		lastId++

		w.WriteHeader(http.StatusCreated)
		w.Write([]byte("created"))

	} else {
		w.WriteHeader(http.StatusBadRequest)
		w.Write([]byte("bad request"))
	}
}
```

2019-10-13 05:30 UTC, sagar-jadhav commented on http_srv.md
> +
Add `readPeople` code snippet as follows:

```
func readPeople(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	err := json.NewEncoder(w).Encode(people)
	if err != nil {
		log.Println(err)
	}
}
```

2019-10-13 05:30 UTC, sagar-jadhav commented on http_srv.md
> +
Add `updatePerson` code snippet here as follows:

```
func updatePerson(w http.ResponseWriter, r *http.Request) {
	id := r.FormValue("id")
	intId, err := strconv.Atoi(id)
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		w.Write([]byte("bad request"))
		return
	}

	person, ok := people[intId]
	if !ok {
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte("not found"))
		return
	}

	person.FirstName = r.FormValue("first_name")
	person.LastName = r.FormValue("last_name")

	people[intId] = person
	w.WriteHeader(http.StatusAccepted)
	w.Write([]byte("updated"))
}
```

2019-10-13 05:30 UTC, sagar-jadhav commented on http_srv.md
> +```
Add `deletePerson` code snippet here as follows:

```
func deletePerson(w http.ResponseWriter, r *http.Request) {
	if r.Method == "DELETE" {
		id := r.FormValue("id")

		idInt, err := strconv.Atoi(id)
		if err != nil {
			log.Println(err)
		}

		_, ok := people[idInt]
		if !ok {
			w.WriteHeader(http.StatusNotFound)
			return
		}

		delete(people, idInt)
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("deleted"))
	} else {
		w.Write([]byte("bad request"))
	}
}
```

2019-10-13 05:30 UTC, sagar-jadhav commented on http_srv.md
> +```
Add a link to `source` code at the end and also link to go back.

2019-10-13 05:33 UTC, sagar-jadhav commented
@davidkroell Excellent Documentation 👍 

I suggested some minor changes please have a look. 

Please also update link in **README** as `./http_srv.html`

2019-10-20 08:21 UTC, davidkroell reviewed
Now updated as requested

2019-10-20 17:19 UTC, sagar-jadhav approved these changes

2019-10-20 17:20 UTC, merged